baseURL: https://preview.giggio.net/
build:
  buildStats:
    enable: true
minify:
  minifyOutput: true
  tdewolff:
    html:
      templateDelims:
        - "<nominify"
        - "nominify>"
privacy:
  googleAnalytics:
    disable: false

caches:
  images:
    dir: :cacheDir/images

imaging:
  hint: photo
  quality: 75
  resampleFilter: Lanczos
